use std::env;
use std::path::PathBuf;

fn main() {
    // Windows DLL exports are handled by #[no_mangle] and extern "C"
    
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let package_name = env::var("CARGO_PKG_NAME").unwrap();
    let output_file = target_dir()
        .join(format!("{}.h", package_name.replace("-", "_")));

    // Generate C header using cbindgen
    cbindgen::Builder::new()
        .with_crate(&crate_dir)  // Fix: borrow instead of move
        .with_language(cbindgen::Language::C)
        .with_pragma_once(true)
        .with_include_guard("CHAOSFORGE_MULTIPLAYER_H")
        .with_autogen_warning("/* This file was automatically generated by cbindgen. Do not modify. */")
        .with_namespace("coreria")
        .with_cpp_compat(true)
        .with_documentation(true)
        .include_item("CPlayerState")
        .include_item("CMatchState")  
        .include_item("CInputAction")
        .include_item("CPerformanceMetrics")
        .include_item("RagdollHandle")
        .include_item("LimbIndex")
        .include_item("FightingStyleId")
        .include_item("STYLE_BRAWLER")
        .include_item("STYLE_STRIKER")
        .include_item("STYLE_PHANTOM")
        .include_item("STYLE_TITAN")
        .rename_item("CPlayerState", "PlayerState")
        .rename_item("CMatchState", "MatchState")
        .rename_item("CInputAction", "InputAction")
        .rename_item("CPerformanceMetrics", "PerformanceMetrics")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(&output_file);

    println!("cargo:rerun-if-changed=src/");
    println!("Generated C header: {}", output_file.display());

    // Link with existing C code if available
    let chaosforge_dir = PathBuf::from(&crate_dir).parent().unwrap().join("chaosforge-game");
    if chaosforge_dir.exists() {
        println!("cargo:rustc-link-search=native={}", chaosforge_dir.display());
        // Would link with compiled C objects here
    }

    // Platform-specific linking
    #[cfg(target_os = "windows")]
    {
        println!("cargo:rustc-link-lib=dylib=opengl32");
        println!("cargo:rustc-link-lib=dylib=glu32");
        println!("cargo:rustc-link-lib=dylib=user32");
    }

    #[cfg(target_os = "linux")]
    {
        println!("cargo:rustc-link-lib=dylib=GL");
        println!("cargo:rustc-link-lib=dylib=GLU");
        println!("cargo:rustc-link-lib=dylib=X11");
    }
}

fn target_dir() -> PathBuf {
    if let Ok(target) = env::var("CARGO_TARGET_DIR") {
        PathBuf::from(target)
    } else {
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("target")
    }
}